### ISSUE TITLE
Business man needs an upper lip

### ISSUE THREAD

**Issue by partybusiness** [partybusiness/supreme#1]

**Comment by git-tmurphy57** [comment]
I'll try to mock-up an upper lip and see what looks alright.

**Comment by git-tmurphy57** [comment]
Here's something I threw together quickly, I just extruded a mouth lip like the bottom part of the head. It looks pretty good I think.

[BusinessMan_Model_v3.fbx.zip](https://github.com/partybusiness/supreme/files/676519/BusinessMan_Model_v3.fbx.zip)
